@AlertVault_HostAddress = http://localhost:5038

GET {{AlertVault_HostAddress}}/api/alert/all
Accept: application/json

###

POST {{AlertVault_HostAddress}}/api/alert
Content-Type: application/json

{
  "Interval": "0.00:01:00.0000",
  "UserId": 1
}

###
DELETE {{AlertVault_HostAddress}}/api/alert/17d18abf-06e9-4299-a9f8-70e04f4a4dc1
###
GET {{AlertVault_HostAddress}}/api/alert/5806b288-4f6a-499c-af5c-2e2f29b59048
Accept: application/json
###
GET {{AlertVault_HostAddress}}/5806b288-4f6a-499c-af5c-2e2f29b59048
###
GET {{AlertVault_HostAddress}}/api/alert/{uuid}/requests
Accept: application/json
###
